# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Dev/Ariadne

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Dev/Ariadne

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Dev/Ariadne/CMakeFiles /home/pi/Dev/Ariadne/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Dev/Ariadne/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ariadne

# Build rule for target.
Ariadne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ariadne
.PHONY : Ariadne

# fast build rule for target.
Ariadne/fast:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/build
.PHONY : Ariadne/fast

Ariadne.o: Ariadne.cpp.o

.PHONY : Ariadne.o

# target to build an object file
Ariadne.cpp.o:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/Ariadne.cpp.o
.PHONY : Ariadne.cpp.o

Ariadne.i: Ariadne.cpp.i

.PHONY : Ariadne.i

# target to preprocess a source file
Ariadne.cpp.i:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/Ariadne.cpp.i
.PHONY : Ariadne.cpp.i

Ariadne.s: Ariadne.cpp.s

.PHONY : Ariadne.s

# target to generate assembly for a file
Ariadne.cpp.s:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/Ariadne.cpp.s
.PHONY : Ariadne.cpp.s

AriadneFiles/DMatchSort.o: AriadneFiles/DMatchSort.cpp.o

.PHONY : AriadneFiles/DMatchSort.o

# target to build an object file
AriadneFiles/DMatchSort.cpp.o:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/AriadneFiles/DMatchSort.cpp.o
.PHONY : AriadneFiles/DMatchSort.cpp.o

AriadneFiles/DMatchSort.i: AriadneFiles/DMatchSort.cpp.i

.PHONY : AriadneFiles/DMatchSort.i

# target to preprocess a source file
AriadneFiles/DMatchSort.cpp.i:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/AriadneFiles/DMatchSort.cpp.i
.PHONY : AriadneFiles/DMatchSort.cpp.i

AriadneFiles/DMatchSort.s: AriadneFiles/DMatchSort.cpp.s

.PHONY : AriadneFiles/DMatchSort.s

# target to generate assembly for a file
AriadneFiles/DMatchSort.cpp.s:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/AriadneFiles/DMatchSort.cpp.s
.PHONY : AriadneFiles/DMatchSort.cpp.s

AriadneFiles/GeoPoint.o: AriadneFiles/GeoPoint.cpp.o

.PHONY : AriadneFiles/GeoPoint.o

# target to build an object file
AriadneFiles/GeoPoint.cpp.o:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/AriadneFiles/GeoPoint.cpp.o
.PHONY : AriadneFiles/GeoPoint.cpp.o

AriadneFiles/GeoPoint.i: AriadneFiles/GeoPoint.cpp.i

.PHONY : AriadneFiles/GeoPoint.i

# target to preprocess a source file
AriadneFiles/GeoPoint.cpp.i:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/AriadneFiles/GeoPoint.cpp.i
.PHONY : AriadneFiles/GeoPoint.cpp.i

AriadneFiles/GeoPoint.s: AriadneFiles/GeoPoint.cpp.s

.PHONY : AriadneFiles/GeoPoint.s

# target to generate assembly for a file
AriadneFiles/GeoPoint.cpp.s:
	$(MAKE) -f CMakeFiles/Ariadne.dir/build.make CMakeFiles/Ariadne.dir/AriadneFiles/GeoPoint.cpp.s
.PHONY : AriadneFiles/GeoPoint.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Ariadne"
	@echo "... edit_cache"
	@echo "... Ariadne.o"
	@echo "... Ariadne.i"
	@echo "... Ariadne.s"
	@echo "... AriadneFiles/DMatchSort.o"
	@echo "... AriadneFiles/DMatchSort.i"
	@echo "... AriadneFiles/DMatchSort.s"
	@echo "... AriadneFiles/GeoPoint.o"
	@echo "... AriadneFiles/GeoPoint.i"
	@echo "... AriadneFiles/GeoPoint.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

